### 发送JSON数据

GET  http://192.168.120.62:9201/mes/cjkb/execute
Content-Type: application/json
//这里必须有一空行

{
  "gc":"1530",
  "lh":"新基地4#",
  "ks":"组测三课",
  "cj":"三课一",
  "sbglcj":"组测三课一车间"
}

### 发送JSON数据

post http://192.168.46.10/mes/cjkb/execute
Content-Type: application/json
//这里必须有一空行

{
  "gc":"1530",
  "lh":"新基地4#",
  "ks":"组测三课",
  "cj":"三课一",
  "sbglcj":"组测三课一车间"
}

### 发送JSON数据

post  http://rap2api.taobao.org/app/mock/283615/mes/cjkb/execute:9999
//rap2模拟数据（时间间隔可以缩小）

{ 
  "gc":"1530",
  "lh":"新基地4#",
  "ks":"组测三课",
  "cj":"三课一",
  "sbglcj":"组测三课一车间"
}